@startuml forms

entity ativo #white;line.bold;line:green {
    <color:green>*id BIGINT NOT NULL <<PK>>
    --
    status VARCHAR (20) NOT NULL
}

entity usuario #white;line.bold;line:red {
    <color:red>*id BIGINT NOT NULL <<PK>>
    <color:green>ativo BIGINT NOT NULL <<FK>>
    --
    nome_usuario VARCHAR(255) NOT NULL
    email_usuario VARCHAR(255) NOT NULL
    login_usuario VARCHAR(255) NOT NULL
    senha_usuario VARCHAR(255) NOT NULL
    data_cadastro_usuario TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    telefone_usuario VARCHAR(40) NOT NULL 
}

entity perfil #white;line.bold;line:blue {
    <color:blue>*id BIGINT NOT NULL <<PK>>
    <color:red>id_usuario BIGINT NOT NULL <<FK>>
    <color:green>ativo BIGINT NOT NULL <<FK>>
    --
    nome_perfil VARCHAR(255) NOT NULL
    data_cadastro_perfil TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

entity sessao #white;line.bold;line:DarkCyan {
    <color:DarkCyan>*id BIGINT NOT NULL <<PK>>
    --
    nome_sessao VARCHAR(255) NOT NULL
    data_cadastro_sessao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

entity perfil_sessao #white;line.bold; {
    *id BIGINT NOT NULL <<PK>>
    <color:blue>id_perfil BIGINT NOT NULL <<FK>>
    <color:DarkCyan>id_sessao BIGINT NOT NULL <<FK>>
}

entity publico #white;line.bold;line:purple {
    <color:purple>*id BIGINT NOT NULL <<PK>>
    <color:red>id_usuario BIGINT NOT NULL <<FK>>
    <color:green>ativo BIGINT NOT NULL <<FK>>
    --
    nome_publico VARCHAR(255) NOT NULL
    data_cadastro_publico TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

entity pergunta_publico #white;line.bold;line:LightCoral {
    <color:LightCoral>*id BIGINT NOT NULL <<PK>>
    <color:purple>id_publico BIGINT NOT NULL <<FK>>
    <color:red>id_usuario BIGINT NOT NULL <<FK>>
    <color:green>ativo BIGINT NOT NULL <<FK>>
    --
    descricao_pergunta TEXT NOT NULL
    data_cadastro_pergunta TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

entity forma_atendimento #white;line.bold;line:SteelBlue {
    <color:SteelBlue>*id BIGINT NOT NULL <<PK>>
    <color:red>id_usuario BIGINT NOT NULL <<FK>>
    <color:green>ativo BIGINT NOT NULL <<FK>>
    --
    nome_atendimento VARCHAR(255) NOT NULL
    data_cadastro_forma TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}

entity atendimento #white;line.bold;line:Orange {
    *<color:Orange>id BIGINT NOT NULL <<PK>>
    <color:SteelBlue>id_forma BIGINT NOT NULL <<FK>>
    <color:LightCoral>id_pergunta BIGINT NOT NULL <<FK>>
    <color:red>id_usuario BIGINT NOT NULL <<FK>>
    <color:green>ativo BIGINT NOT NULL <<FK>>
    --
    data_cadastro_atendimento TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    resposta_atendimento TEXT NOT NULL
}

ativo ||-[#green]-|| perfil
ativo ||-[#green]-|| usuario
ativo ||-[#green]-|| forma_atendimento
ativo ||-[#green]-|| publico
ativo ||-[#green]-|| pergunta_publico
ativo ||-[#green]-|| atendimento
sessao ||-[#DarkCyan]left-|{ perfil_sessao
perfil ||-[#blue]down-|{ perfil_sessao
perfil }|-[#blue]left-|| usuario
usuario ||-[#red]up-|{ atendimento
usuario ||-[#red]-|{ forma_atendimento
usuario ||-[#red]left-|{ publico
usuario ||-[#red]-|{ pergunta_publico
publico ||-[#purple]-|{ pergunta_publico
atendimento }|-[#SteelBlue]up-|| forma_atendimento
atendimento }|-[#LightCoral]up-|| pergunta_publico

@enduml